services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data


  redis:
    image: "redis:latest"
    restart: unless-stopped
    ports:
      - "6379:6379"


  counter_app:
    container_name: "counter_app"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - custom


  celery_worker:
    container_name: "celery_worker"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    networks:
      - custom
    command: ["celery", "-A", "counter_water", "worker", "--loglevel=info"]
 

networks:
  custom:
    driver: bridge

volumes:
  db-data: