services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - custom

  counter_app:
    container_name: counter_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - custom
    command: ["./server-entrypoint.sh"]
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: '5432'
      REDIS_HOST: redis
      REDIS_PORT: '6379'

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - counter_app
    networks:
      - custom
    volumes:
      - .:/app
    # command: ["./worker-entrypoint.sh"]
    command: celery -A counter_water worker --loglevel=INFO
 
networks:
  custom:
    driver: bridge

volumes:
  db-data: