# Generated by Django 5.0.7 on 2024-07-20 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Общая площадь дома')),
                ('address', models.CharField(max_length=256, unique=True, verbose_name='Адрес дома')),
            ],
            options={
                'verbose_name': 'Многоквартирный жилой дом',
                'verbose_name_plural': 'Многоквартирные жилые дома',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_type', models.CharField(choices=[('cold_water_for_flat', 'холодное водоснабжение в квартире'), ('hot_water_for_flat', 'хорячее водоснабжение в квартире'), ('cold_water_for_apartment_building', 'холодное водоснабжение для общего имущества'), ('hot_water_for_apartment_building', 'хорячее водоснабжение для общего имущества')], max_length=124, verbose_name='Тип тарифа водоснабжения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость одного кубического метра')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер квартиры')),
                ('number_of_registered', models.PositiveIntegerField(default=1, verbose_name='Количество зарегистрированных лиц')),
                ('area', models.DecimalField(decimal_places=6, max_digits=6, verbose_name='Площадь квартиры')),
                ('apartment_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_building', to='counter.apartmentbuilding', verbose_name='Дом, где расположена квартира')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='WaterCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10, verbose_name='Серийный номер счетчика')),
                ('verification_date', models.DateField(verbose_name='Дата поверки')),
                ('type_water_counter', models.CharField(choices=[('cold', 'холодное'), ('hot', 'горячее')], max_length=8, verbose_name='Тип водоснабжения')),
                ('meters', models.JSONField(default=list, verbose_name='Показания счетчика')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='counter.flat', verbose_name='Квартира')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff', to='counter.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчики',
            },
        ),
    ]
