# Generated by Django 5.0.7 on 2024-07-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая площадь дома'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.CharField(choices=[('cold_water_for_flat', 'холодное водоснабжение в квартире'), ('hot_water_for_flat', 'хорячее водоснабжение в квартире'), ('cold_water_for_apartment_building', 'холодное водоснабжение для общего имущества'), ('hot_water_for_apartment_building', 'хорячее водоснабжение для общего имущества'), ('maintenance of common property', 'содержание общего имущества')], max_length=124, verbose_name='Тип тарифа водоснабжения'),
        ),
    ]
