# Generated by Django 5.0.7 on 2024-07-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_alter_apartmentbuilding_total_area_alter_flat_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.CharField(choices=[('cold_water_for_flat', 'холодное водоснабжение в квартире'), ('hot_water_for_flat', 'хорячее водоснабжение в квартире'), ('cold_water_for_apartment_building', 'холодное водоснабжение для общего имущества'), ('hot_water_for_apartment_building', 'хорячее водоснабжение для общего имущества'), ('maintenance_of_common_property', 'содержание общего имущества')], max_length=124, verbose_name='Тип тарифа водоснабжения'),
        ),
        migrations.AddConstraint(
            model_name='flat',
            constraint=models.UniqueConstraint(fields=('number', 'apartment_building'), name='unique_flat_in_building'),
        ),
        migrations.AddConstraint(
            model_name='watercounter',
            constraint=models.UniqueConstraint(fields=('serial_number', 'flat'), name='unique_water_counter_in_flat'),
        ),
    ]
