# Generated by Django 5.0.7 on 2024-07-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_alter_tariff_tariff_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watercounter',
            name='tariff',
        ),
        migrations.AlterField(
            model_name='watercounter',
            name='meters',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Показания счетчика'),
        ),
    ]
