# Generated by Django 5.0.7 on 2024-07-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_remove_watercounter_tariff_alter_watercounter_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='apartment_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='counter.apartmentbuilding', verbose_name='Дом, где расположена квартира'),
        ),
        migrations.AlterField(
            model_name='watercounter',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_counters', to='counter.flat', verbose_name='Квартира'),
        ),
    ]
