# Generated by Django 5.0.7 on 2024-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_alter_flat_apartment_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='calculations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Расчеты'),
        ),
    ]
