# Generated by Django 5.0.7 on 2024-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_flat_calculations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.CharField(choices=[('cold_water_for_flat_counter', 'холодное водоснабжение в квартире (по счетчику)'), ('hot_water_for_flat_counter', 'горячее водоснабжение в квартире (по счетчику)'), ('cold_water_standard', 'холодное водоснабжение в квартире (по нормативу)'), ('hot_water_standard', 'горячее водоснабжение в квартире (по нормативу)'), ('maintenance_of_common_property', 'содержание общего имущества')], max_length=124, verbose_name='Тип тарифа водоснабжения'),
        ),
    ]
