# Generated by Django 5.0.7 on 2024-07-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_alter_tariff_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.CharField(choices=[('cold_water_for_flat', 'холодное водоснабжение в квартире'), ('hot_water_for_flat', 'горячее водоснабжение в квартире'), ('maintenance_of_common_property', 'содержание общего имущества')], max_length=124, verbose_name='Тип тарифа водоснабжения'),
        ),
    ]
